GET http://localhost:3000/campaigns

###

POST http://localhost:3000/campaigns

{
    "name": "mouse 6",
    "content": "change password",
    "emails": ["test1@gmail.com", "test2@gmail.com", "test3@gmail.com"]
}

###

GET http://localhost:3000/campaigns/d1amve9mcbhp6ocoi3k0

###

DELETE http://localhost:3000/d1amve9mcbhp6ocoi3k0