GET http://localhost:3000/campaigns

###

POST http://localhost:3000/campaigns

{
    "name": "mouse 6",
    "content": "change password",
    "emails": ["test1@gmail.com", "test2@gmail.com", "test3@gmail.com"]
}

###

GET http://localhost:3000/campaigns/d1amve9mcbhp6ocoi3k0

###

DELETE http://localhost:3000/d1amve9mcbhp6ocoi3k0

###

POST http://localhost:8080/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailn&client_secret=HJc6H9tzfsIY855iYlFJ2zvxOGOiNycq&grant_type=client_credentials

###

POST http://localhost:8080/realms/provider/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=emailn_users&username=duzihd@gmail.com&password=123456&grant_type=password